import DNN_no_window
layer=[2]
nodes=[200]
#timpstep = 10
for i in range(len(layer)):
    for j in range(len(nodes)):
        #DNN_no_window.FineTuneDNN(layer[i], nodes[j], 2, 0.1)
        #DNN_no_window.FineTuneDNN(layer[i], nodes[j], 2, 0.2)
        #DNN_no_window.FineTuneDNN(layer[i], nodes[j], 2, 0.3)
        #DNN_no_window.FineTuneDNN(layer[i], nodes[j], 2, 0.4)
        #DNN_no_window.FineTuneDNN(layer[i], nodes[j], 2, 0.5)
        #DNN_no_window.FineTuneDNN(layer[i], nodes[j], 2, 0.6)
        #DNN_no_window.FineTuneDNN(layer[i], nodes[j], 2, 0.7)
        #DNN_no_window.FineTuneDNN(layer[i], nodes[j], 2, 0.8)
        #DNN_no_window.FineTuneDNN(layer[i], nodes[j], 2, 0.9)
        #DNN_no_window.FineTuneDNN_non_chord_tone_shuffle(layer[i], nodes[j], 2, 1, 10)
        #DNN_no_window.FineTuneDNN_non_chord_tone_shuffle(layer[i], nodes[j], 3, 1, 10)
        #DNN_no_window.FineTuneDNN_non_chord_tone_shuffle(layer[i], nodes[j], 4, 1, 10)
        #DNN_no_window.FineTuneDNN_non_chord_tone_shuffle(layer[i], nodes[j], 5, 1, 10)
        #DNN_no_window.FineTuneDNN_non_chord_tone(layer[i], nodes[j], 0, 1, 'LSTM', 10)
        #DNN_no_window.FineTuneDNN_non_chord_tone(layer[i], nodes[j], 1, 1)
        #DNN_no_window.FineTuneDNN_non_chord_tone(layer[i], nodes[j], 1, 0.2)
        #DNN_no_window.FineTuneDNN_non_chord_tone(layer[i], nodes[j], 1, 0.3)
        #DNN_no_window.FineTuneDNN_non_chord_tone(layer[i], nodes[j], 1, 0.4)
        #DNN_no_window.FineTuneDNN_non_chord_tone(layer[i], nodes[j], 1, 0.5)
        #DNN_no_window.FineTuneDNN_non_chord_tone(layer[i], nodes[j], 1, 0.6)
        #DNN_no_window.FineTuneDNN_non_chord_tone(layer[i], nodes[j], 1, 0.7)
        #DNN_no_window.FineTuneDNN_non_chord_tone(layer[i], nodes[j], 1, 0.8)
        DNN_no_window.FineTuneDNN_non_chord_tone(layer[i], nodes[j], 1, 1, 'DNN', 10)
        #DNN_no_window.FineTuneDNN_non_chord_tone(layer[i], nodes[j], 1, 1, 'LSTM', 10)
        #DNN_no_window.FineTuneDNN_non_chord_tone(layer[i], nodes[j], 0, 1, 'RNN', 10)
        #DNN_no_window.FineTuneDNN_non_chord_tone(layer[i], nodes[j], 0, 1, 'DNN', 10)
        #DNN_no_window.FineTuneDNN_non_chord_tone(layer[i], nodes[j], 1, 0.5, 'DNN', 10)
        #DNN_no_window.FineTuneDNN_non_chord_tone(layer[i], nodes[j], 1, 0.6, 'DNN', 10)
        #DNN_no_window.FineTuneDNN_non_chord_tone(layer[i], nodes[j], 1, 0.7, 'DNN', 10)
        #DNN_no_window.FineTuneDNN_non_chord_tone(layer[i], nodes[j], 1, 0.8, 'DNN', 10)
        #DNN_no_window.FineTuneDNN_non_chord_tone(layer[i], nodes[j], 1, 0.9, 'DNN', 10)
        #DNN_no_window.FineTuneDNN_non_chord_tone(layer[i], nodes[j], 1, 1, 'DNN', 10)
        #DNN_no_window.FineTuneDNN_non_chord_tone(2, 100, 1, 1, 'RNN', 5)
        #DNN_no_window.FineTuneDNN_non_chord_tone(layer[i], nodes[j], 0, 1, 'RNN', 10)
        #DNN_no_window.FineTuneDNN_non_chord_tone(layer[i], 100, 0, 0.5, 'RNN', 10)
        #DNN_no_window.FineTuneDNN_non_chord_tone(layer[i], 100, 0, 0.6, 'RNN', 10)
        #DNN_no_window.FineTuneDNN_non_chord_tone(layer[i], 100, 0, 0.7, 'RNN', 10)
        #DNN_no_window.FineTuneDNN_non_chord_tone(layer[i], 100, 0, 0.8, 'RNN', 10)
        #DNN_no_window.FineTuneDNN_non_chord_tone(layer[i], 200, 0, 1, 'RNN', 10)
        #DNN_no_window.FineTuneDNN_non_chord_tone(layer[i], 100, 0, 0.5, 'LSTM', 10)
        #DNN_no_window.FineTuneDNN_non_chord_tone(layer[i], 100, 0, 0.6, 'LSTM', 10)
        #DNN_no_window.FineTuneDNN_non_chord_tone(layer[i], 100, 0, 0.7, 'LSTM', 10)
        #DNN_no_window.FineTuneDNN_non_chord_tone(layer[i], 100, 0, 0.8, 'LSTM', 10)
        #DNN_no_window.FineTuneDNN_non_chord_tone(layer[i], 100, 0, 0.9, 'LSTM', 10)
        #DNN_no_window.FineTuneDNN_non_chord_tone(layer[i], 50, 0, 1, 'LSTM', 10)

        #DNN_no_window.FineTuneDNN_non_chord_tone(layer[i], 100, 1, 1, 'LSTM', 5)
        #DNN_no_window.FineTuneDNN_non_chord_tone(layer[i], nodes[j], 0, 1, 'BLSTM', 10)
        #DNN_no_window.FineTuneDNN_non_chord_tone(layer[i], nodes[j], 2, 1, 'BLSTM', 10)
        #DNN_no_window.FineTuneDNN_non_chord_tone(layer[i], nodes[j], 3, 1, 'BLSTM', 10)
        #DNN_no_window.FineTuneDNN_non_chord_tone(layer[i], nodes[j], 4, 1, 'BLSTM', 10)
        #DNN_no_window.FineTuneDNN_non_chord_tone(layer[i], nodes[j], 5, 1, 'BLSTM', 10)
        #DNN_no_window.FineTuneDNN_non_chord_tone(layer[i], nodes[j], 2, 1)
        #DNN_no_window.FineTuneDNN_non_chord_tone(layer[i], nodes[j], 3, 1)
        #DNN_no_window.FineTuneDNN(layer[i],nodes[j],1,1)
        #DNN_no_window.FineTuneDNN(layer[i], nodes[j], 2, 1)
        #DNN_no_window.FineTuneDNN(layer[i],nodes[j],3,1)
        #DNN_no_window.FineTuneDNN(layer[i],nodes[j],4,1)
        #DNN_no_window.FineTuneDNN(layer[i],nodes[j],5,1)


#DNN_AMH_debug.FineTuneDNN(2,500)
